name: 'Verify site build'

on: pull_request

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install bundle command
        run: gem install bundler
      - name: Install ruby dependencies
        run: cd SourceCode && bundle install
      - name: Copy robots.txt in to place
        run: cp ./BuildAdditions/robots.txt ./SourceCode/
      - name: Copy the PRODUCTION _config.yml in to place
        run: cp ./BuildAdditions/prod_config.yml ./SourceCode/_config.yml
      - name: Build the site via Jekyll
        run: cd SourceCode && bundle exec jekyll build
      - name: Deploy AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: End without pushing
        run: echo "No deployments happen during PR"
